-- DROP TABLE IF EXISTS categories CASCADE;
-- CREATE TABLE categories (
--   id SERIAL PRIMARY KEY NOT NULL,
--   name VARCHAR(255) NOT NULL
-- );

DROP TABLE IF EXISTS tasks CASCADE;
CREATE TABLE tasks (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(255)
  -- category_id INTEGER REFERENCES categories(id) ON DELETE CASCADE
);
